### ISSUE TITLE
Seems impossible to install the lastest version

### ISSUE THREAD

**Issue by ErnestAbbott** [intelllex/react-pdf#12]
Looks a great package, but I can't install it.
1. download the coded and followed the install instructions. Hours later the install failed.  Snipped of failed log is below.

15282 info run core-js@2.6.12 postinstall { code: 0, signal: null }
15283 timing build:run:postinstall:node_modules/@babel/polyfill/node_modules/core-js Completed in 983ms
15284 info run uglifyjs-webpack-plugin@0.4.6 postinstall node_modules/webpack/node_modules/uglifyjs-webpack-plugin node lib/post_install.js
15285 info run core-js@2.6.12 postinstall { code: 0, signal: null }
15286 timing build:run:postinstall:node_modules/babel-plugin-transform-decorators-legacy/node_modules/core-js Completed in 950ms
15287 info run uglifyjs-webpack-plugin@0.4.6 postinstall { code: 0, signal: null }
15288 timing build:run:postinstall:node_modules/webpack/node_modules/uglifyjs-webpack-plugin Completed in 181ms
15289 info run inferno@7.4.8 postinstall { code: 0, signal: null }
15290 timing build:run:postinstall:node_modules/inferno Completed in 3126ms
15291 info run node-sass@4.14.1 postinstall { code: 1, signal: null }
15292 timing reify:rollback:createSparse Completed in 591755ms
15293 timing reify:rollback:retireShallow Completed in 12109ms
15294 timing command:install Completed in 2368676ms
15295 verbose stack Error: command failed
15295 verbose stack     at ChildProcess.<anonymous> (C:\Users\Ernest\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
15295 verbose stack     at ChildProcess.emit (node:events:369:20)
15295 verbose stack     at maybeClose (node:internal/child_process:1067:16)
15295 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
15296 verbose pkgid node-sass@4.14.1
15297 verbose cwd C:\Users\Ernest\Downloads\react-pdf-master_3
15298 verbose Windows_NT 10.0.19042
15299 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ernest\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
15300 verbose node v15.12.0
15301 verbose npm  v7.5.6
15302 error code 1
15303 error path C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-sass
15304 error command failed
15305 error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
15306 error Building: C:\Program Files\nodejs\node.exe C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
15307 error gyp info it worked if it ends with ok
15307 error gyp verb cli [
15307 error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
15307 error gyp verb cli   'C:\\Users\\Ernest\\Downloads\\react-pdf-master_3\\node_modules\\node-gyp\\bin\\node-gyp.js',
15307 error gyp verb cli   'rebuild',
15307 error gyp verb cli   '--verbose',
15307 error gyp verb cli   '--libsass_ext=',
15307 error gyp verb cli   '--libsass_cflags=',
15307 error gyp verb cli   '--libsass_ldflags=',
15307 error gyp verb cli   '--libsass_library='
15307 error gyp verb cli ]
15307 error gyp info using node-gyp@3.8.0
15307 error gyp info using node@15.12.0 | win32 | x64
15307 error gyp verb command rebuild []
15307 error gyp verb command clean []
15307 error gyp verb clean removing "build" directory
15307 error gyp verb command configure []
15307 error gyp verb check python checking for Python executable "python2" in the PATH
15307 error gyp verb `which` failed Error: not found: python2
15307 error gyp verb `which` failed     at getNotFoundError (C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\node_modules\which\which.js:13:12)
15307 error gyp verb `which` failed     at F (C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\node_modules\which\which.js:68:19)
15307 error gyp verb `which` failed     at E (C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\node_modules\which\which.js:80:29)
15307 error gyp verb `which` failed     at C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\node_modules\which\which.js:89:16
15307 error gyp verb `which` failed     at C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\node_modules\isexe\index.js:42:5
15307 error gyp verb `which` failed     at C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\node_modules\isexe\windows.js:36:5
15307 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21)
15307 error gyp verb `which` failed  python2 Error: not found: python2
15307 error gyp verb `which` failed     at getNotFoundError (C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\node_modules\which\which.js:13:12)
15307 error gyp verb `which` failed     at F (C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\node_modules\which\which.js:68:19)
15307 error gyp verb `which` failed     at E (C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\node_modules\which\which.js:80:29)
15307 error gyp verb `which` failed     at C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\node_modules\which\which.js:89:16
15307 error gyp verb `which` failed     at C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\node_modules\isexe\index.js:42:5
15307 error gyp verb `which` failed     at C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-gyp\node_modules\isexe\windows.js:36:5
15307 error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:193:21) {
15307 error gyp verb `which` failed   code: 'ENOENT'
15307 error gyp verb `which` failed }
15307 error gyp verb check python checking for Python executable "python" in the PATH
15307 error gyp verb `which` succeeded python C:\Python39\python.EXE
15307 error gyp ERR! configure error
15307 error gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
15307 error gyp ERR! stack   File "<string>", line 1
15307 error gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
15307 error gyp ERR! stack                       ^
15307 error gyp ERR! stack SyntaxError: invalid syntax
15307 error gyp ERR! stack
15307 error gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
15307 error gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
15307 error gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
15307 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
15307 error gyp ERR! System Windows_NT 10.0.19042
15307 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ernest\\Downloads\\react-pdf-master_3\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
15307 error gyp ERR! cwd C:\Users\Ernest\Downloads\react-pdf-master_3\node_modules\node-sass
15307 error gyp ERR! node -v v15.12.0
15307 error gyp ERR! node-gyp -v v3.8.0
15307 error gyp ERR! not ok
15307 error Build failed with error code: 1
15308 verbose exit 1

**Comment by trinhngocdieu** [comment]
@ErnestAbbott : 
Can you try to use with lower version of nodejs (14.0 or 10.7.0)? 
Maybe this package has not been compatible with node 15.0 yet.

**Comment by ErnestAbbott** [comment]
Hi Trinh Ngoc Dieu

Thank you for taking the time to reply. Very much appreciated.
Unfortunately, I don't think that I can downgrade my project at the
present. I'm on a very very tight deadline. I thought I had 3 months left
to finish, just been told I have only 3 weeks. 🤔
While I'd like to use this package, the company has decided to go for a
purchased package because of the very tight deadline. So sad.
Regards
Ernest

**Comment by CarltonCassedy** [comment]
2+ years later, hope your project went well. Just experienced pretty much this exact same issue trying to install this package. The error output I have is nearly identical, using node 18.16.0 though.
